### ISSUE TITLE
Shared Journal Link not Possible

### ISSUE THREAD

**Issue by H1ghSyst3m** [tybayn/phasmo-cheat-sheet-de#3]
Hello,

I don't know if it should be so, but in the DE version that "Shared Journal Link ("Geteilte Link vom Journal)" does not work.

Also at the bottom left Active Users: undefined is displayed.

If it should work, what do I have to consider? Where do I have to check? What does the server need to work?

**Comment by tybayn** [comment]
Thanks for reaching out! This is actually still a work in progress and I am actively working with my group of translators to get this site working. Once it's complete, the site will be live at https://tybayn.github.io/phasmo-cheat-sheet-de/

We anticipate having it completed sometime next week.

Note: Journal link, desktop link, and active users are handled through a proprietary backend that uses ip lookup to only allow connections from certain websites and ips.

**Comment by H1ghSyst3m** [comment]
Thanks for the fast reply.  😊

I am very happy to hear that there will be a live version for DE. 

Currently, I have the code running on my server. Because I like to play with my friends and they can't speak english very well.

Site: https://phasm.sinmundus.com/

If you need any support. At the moment I have translated the Taro Cards myself and will work out the guides, til the live version is out.
